#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '💪  Running application to test that everything is fine...'

# Check testing
pnpm test ||
(
    echo '🤡😂❌🤡 Test check failed. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can push
echo '✅✅✅✅ You win this time... I am pushing this now. ✅✅✅✅'
